version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit loopback_users []"

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  order-service:
    build: ../
    command: ["/app/order-service"]
    environment:
      APP_HTTP_ADDR: ":8080"
      MONGO_URI: "mongodb://mongo:27017"
      MONGO_DB: "ecommerce"
      RABBIT_URI: "amqp://guest:guest@rabbitmq:5672/"
      EVENTS_EXCHANGE: "ecommerce.events"
      SERVICE_NAME: "order-service"
      LOG_LEVEL: "info"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - rabbitmq

volumes:
  mongo_data:
